### ISSUE TITLE
你好，能做个模拟知乎登录的嘛？好多是三四年前的。看着只有你的在更新。

### ISSUE THREAD

**Issue by wcyy** [anotherfre/demo_scrapy#2]
好多人的都不更新了说有错误，你好能做个知乎更新的嘛

**Comment by anotherfre** [comment]
我有空试下 弄好了回复你

**Comment by anotherfre** [comment]
https://github.com/anotherfre/demo_scrapy/blob/master/ZhiHULogin/zhihu_login.py
这个用chromedriver自动登录
